### ISSUE TITLE
resize window and hide menu bar

### ISSUE THREAD

**Issue by nhatanhnguyenbui** [nhatanhnguyenbui/fatilewebsite#5]
@huy121234 when i resize the window, nothing changes. it looks terrible. can you please add some to resize the layout when the size of window change and if it's small enough hide the menu bar

<img width="704" alt="Screen Shot 2020-04-12 at 9 01 40 AM" src="https://user-images.githubusercontent.com/56037106/79058781-6c2f4100-7c9c-11ea-9ae6-17b97dd6c857.png">

**Comment by huy121234** [comment]
I just fininished fix it. The menu bar is hidden when the windows is minimized, you can check it
